### ISSUE TITLE
Question: Should there be a 'Super-'Key?

### ISSUE THREAD

**Issue by AxelMKlein** [nick-shmyrev/improved-osk-gnome-ext#43]
Hi *,

First, thank you so much for creating and maintaining this Gnome extension. Great stuff!

Now, at my instance, I don't see a 'Super'-Key.

Is this intended? In case yes, are there reasons for this and can it be brought in?
Or do I do something wrong?

Thank you and best regards
Axel

**Comment by nick-shmyrev** [comment]
Yes, that was somewhat intended. I never used it, so when I was rewriting the extension for Gnome 43 I just didn't bring it back.
What's your use case for it? I don't mind adding it back in if enough people need it.

Also, you can add it yourself if you want. Start by cloning this repo. All of the OSK layouts are located in `/src/data/osk-layouts` dir. Layouts are divided into levels (lowercase chars, uppercase chars, numbers, other symbols), and each level consists of multiple lines. You'd probably want to add the SUPER key to both lowercase and uppercase char levels to keep the look of your language layout consistent. If so, don't forget to decrease the spacebar key width to compensate for an extra key. This is the code for SUPER key:
```js
{
  "action": "modifier",
  "keyval": "0xffeb",
  "label": "◆"
},
```
If you want to use it in key combinations, keep the `"action": "modifier"` part, otherwise remove it.

Once you've modified your preferred layout, run the `package-extension.sh` from the root of the project, then continue with the manual installation process (see [README](https://github.com/nick-shmyrev/improved-osk-gnome-ext#from-source-code)).
